apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.zomato.name }}
  labels:
    app: {{ .Values.zomato.app }}
spec:
  type: {{ .Values.zomato.type }}
  ports:
    - port: {{ .Values.zomato.port }}
      targetPort: {{ .Values.zomato.targetPort }}
      
  selector:
    app: {{ .Values.zomato.app }}
